---
- name: Converge
  hosts: all
  vars:
    pip_install_method: get-pip
    pip_packages:
      - pipx
      - http
      - jq
  tasks:
    - name: "Include ansible-role-pip"
      ansible.builtin.include_role:
        name: "ansible-role-pip"
