---
- name: Converge
  hosts: all
  vars:
    pip_packages:
      - ansible-core
      - pipx
    pip_extra_args: "--user"
  tasks:
    - name: "Include ansible-role-pip"
      ansible.builtin.include_role:
        name: "ansible-role-pip"
