---
dependency:
  name:                      galaxy
  enabled:                   false
driver:
  name:                      docker
lint:                        |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name:                    molecule-${DKR_IMAGE:-debian11}
    hostname:                ${DKR_IMAGE:-debian11}
    image:                   ghcr.io/pandemonium1986/${DKR_IMAGE:-debian11}:nightly
    pull:                    true
    pre_build_image:         true
    tty:                     true
    override_command:        false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged:              true
provisioner:
  name:                      ansible
  playbooks:
    verify:                  ../resources/verify.yml
    prepare:                 ../resources/prepare.yml
  lint:                      |
    set -e
    ansible-lint
  config_options:
    defaults:
      stdout_callback:       yaml
      bin_ansible_callbacks: true
scenario:
  name:                      get-pip
verifier:
  name:                      ansible
  enabled:                   true
