---
- name:                          import assert.yml
  ansible.builtin.import_tasks:  assert.yml
  run_once:                      true
  delegate_to:                   localhost

- name:                          Include Family specific variables
  ansible.builtin.include_vars:  "{{ ansible_os_family }}-Family.yml"

- name:                          Include Family specific tasks
  ansible.builtin.include_tasks: setup-{{ ansible_os_family }}.yml

- name:                          Include fact generation
  ansible.builtin.include_tasks: fact.yml

- name:                          Installation of prerequisite packages
  package:
    name:                        "{{ _packages }}"
    state:                       present

- name:                          Install pip with the package manager
  package:
    name:                        "{{ _package_pip }}"
    state:                       present
  when:                          pip_install_method == 'package'

- name:                          Update pip install by the package manager
  ansible.builtin.pip:
    name:                        "pip"
    state:                       latest
    executable:                  "{{ _pip_executable }}"
  when:
    - pip_install_package_update | bool
    - pip_install_method == 'package'

- name:                          Install pip with the get-pip bootstrap script
  block:
    - name:                      "Ensure {{ _package_pip }} is absent"
      package:
        name:                    "{{ _package_pip }}"
        state:                   absent
      when:                      ansible_os_family == 'Debian'
    - name:                      Ensure .cache directory exists
      file:
        path:                    /root/.cache
        state:                   directory
        mode:                    0700
    - name:                      Download get_pip.py
      get_url:
        url:                     https://bootstrap.pypa.io/get-pip.py
        dest:                    /root/.cache/get-pip.py
        mode:                    0600
    - name:                      Run get-pip.py
      command:                   "{{ _python_executable }} get-pip.py"
      args:
        chdir:                   /root/.cache
        creates:                 /root/.cache/pip_install_done
      register:                  get_pip_result
    # - debug:
    #     var:                   get_pip_result
    - name:                      Ensure pip installation is done
      file:
        path:                    /root/.cache/pip_install_done
        state:                   touch
        mode:                    0700
      when:                      get_pip_result.changed
  become:                        true
  become_user:                   root
  when:                          pip_install_method == 'get-pip'

- name:                          Install pip packages as pip_user
  ansible.builtin.pip:
    name:                        "{{ pip_packages }}"
    state:                       present
    executable:                  "{{ _pip_executable }}"
    extra_args:                  "{{ pip_extra_args | default(omit) }}"
  become:                        true
  become_user:                   "{{ pip_user }}"
