---
- name:                      Include OS-specific variables (Debian).
  include_vars:              "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when:                      ansible_os_family == 'Debian'

- name:                      Include OS-specific variables (RedHat).
  include_vars:              "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when:                      ansible_os_family == 'RedHat'

- name:                      Install packages
  package:
    name:                    "{{ _packages }}"
    state:                   present

- name:                      Set python version (Ubuntu)
  set_fact:
    ansible_install_python: python3
  when:                      (ansible_distribution  == 'Ubuntu') or (ansible_distribution  == 'Linux Mint')

- name:                      Set python version (Redhat/Debian)
  set_fact:
    ansible_install_python: python
  when:                      (ansible_distribution == 'Debian')or (ansible_os_family == 'RedHat')

- name:                      Download and install pip
  block:
    - name:                  Ensure .cache directory exists
      file:
        path:                /root/.cache
        state:               directory
        mode:                0700
    - name:                  Download get_pip.py
      get_url:
        url:                 https://bootstrap.pypa.io/get-pip.py
        dest:                /root/.cache/get-pip.py
        mode:                0600
    - name:                  Run get-pip.py
      command:               "{{ ansible_install_python }} get-pip.py"
      args:
        chdir:               /root/.cache
        creates:             /root/.cache/pip_install_done
      register:              get_pip_result
    # - debug:
    #     var:               get_pip_result
    - name:                  Ensure pip installation is done
      file:
        path:                /root/.cache/pip_install_done
        state:               touch
        mode:                0700
      when:                  get_pip_result.changed
  become:                    true
  become_user:               root
