---
- name:                          import assert.yml
  ansible.builtin.import_tasks:  assert.yml
  run_once:                      true
  delegate_to:                   localhost

- name:                          Configure Mint Fact
  ansible.builtin.set_fact:
    ansible_distribution:        "Mint"
  when:                          ansible_distribution == 'Linux Mint'

- name:                          Include Family specific variables
  ansible.builtin.include_vars:  "{{ ansible_os_family }}-Family.yml"

- name:                          Include Family specific tasks
  ansible.builtin.include_tasks: setup-{{ ansible_os_family }}.yml

- name:                          Configure pip path with package installation
  ansible.builtin.set_fact:
    _pip_executable:             "/usr/bin/{{ _pip_executable }}"
  when:                          pip_install_method == 'package'

- name:                          Configure pip path with get-pip installation
  ansible.builtin.set_fact:
    _pip_executable:             "/usr/local/bin/{{ _pip_executable }}"
  when:                          pip_install_method == 'get-pip'

- name:                          Generate pip_packages list
  ansible.builtin.set_fact:
    pip_packages:                "{{ _pip_mandatory_packages + pip_packages  }}"

- name:                          Force python version to python3
  set_fact:
    ansible_python_interpreter:  python3

- name:                          Installation of prerequisite packages
  package:
    name:                        "{{ _packages }}"
    state:                       present

- name:                          Installing pip with the package manager
  package:
    name:                        "{{ _package_pip }}"
    state:                       present
  when:                          pip_install_method == 'package'


- name:                          Installing pip with the get-pip
  block:
    - name:                      "Ensure {{ _package_pip }} is absent"
      package:
        name:                    "{{ _package_pip }}"
        state:                   absent
      when:                      ansible_os_family == 'Debian'
    - name:                      Ensure .cache directory exists
      file:
        path:                    /root/.cache
        state:                   directory
        mode:                    0700
    - name:                      Download get_pip.py
      get_url:
        url:                     https://bootstrap.pypa.io/get-pip.py
        dest:                    /root/.cache/get-pip.py
        mode:                    0600
    - name:                      Run get-pip.py
      command:                   "{{ ansible_python_interpreter }} get-pip.py"
      args:
        chdir:                   /root/.cache
        creates:                 /root/.cache/pip_install_done
      register:                  get_pip_result
    # - debug:
    #     var:                   get_pip_result
    - name:                      Ensure pip installation is done
      file:
        path:                    /root/.cache/pip_install_done
        state:                   touch
        mode:                    0700
      when:                      get_pip_result.changed
  become:                        true
  become_user:                   root
  when:                          pip_install_method == 'get-pip'

- name:                          Installing pip packages
  ansible.builtin.pip:
    name:                        "{{ pip_packages }}"
    state:                       present
    executable:                  "{{ _pip_executable }}"
    extra_args:                  "{{ pip_extra_args | default(omit) }}"
  become:                        true
  become_user:                   "{{ pip_user }}"
