---
- name: Ensure you are root for the installation
  become: true
  become_user: root
  block:
    - name: "Ensure _packages_pip is absent"
      ansible.builtin.package:
        name: "{{ _packages_pip }}"
        state: absent
      when: ansible_os_family == 'Debian'
    - name: Ensure .cache directory exists
      ansible.builtin.file:
        path: /root/.cache
        state: directory
        mode: 0700
    - name: Download get_pip.py
      ansible.builtin.get_url:
        url: "https://bootstrap.pypa.io/pip/{{ _get_pip_version | default('') }}/get-pip.py"
        dest: /root/.cache/get-pip.py
        mode: 0600
    - name: Run get-pip.py
      ansible.builtin.command: "{{ _python_executable }} get-pip.py"
      args:
        chdir: /root/.cache
        creates: /root/.cache/pip_install_done
      register: get_pip_result
    # - debug:
    #     var: get_pip_result
    - name: Ensure pip installation is done # noqa: no-handler
      ansible.builtin.file:
        path: /root/.cache/pip_install_done
        state: touch
        mode: 0700
      when: get_pip_result.changed
