---
- name: Ensure apt cache is update
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Ensure python3 is install
  ansible.builtin.apt:
    name: python3
    state: present
