---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Run pip as a non-privileged user
      become: true
      become_user: pandemonium
      become_method: ansible.builtin.su
      become_flags: "-"
      ansible.builtin.import_tasks: verify-tests.yml
