---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Run pip as a non-privileged user
      become: true
      become_user: pandemonium
      ansible.builtin.import_tasks: verify-tests.yml
    - name: Run pip as a privileged user
      become: true
      become_user: root
      ansible.builtin.import_tasks: verify-tests.yml
