---
- name:                 Converge
  hosts:                all
  vars:
    pip_install_method: package
    pip_packages:
      - ansible~=2.9
      - ansible-lint
      - molecule[docker]~=3.0
  tasks:
    - name:             "Include ansible-role-pip"
      include_role:
        name:           "ansible-role-pip"
