---
name: "Molecule"
on:
  schedule:
    - cron: "0 21 * * *"
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: "Ansible: Lint"
    runs-on: ubuntu-20.04
    steps:
      - name: "Init: Run checkout"
        uses: actions/checkout@v4
      - name: "Ansible: Lint role"
        uses: ansible/ansible-lint@main
        with:
          args: "--exclude .github .pre-commit-config.yaml"
  molecule-package:
    name: "Molecule: package scenario"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        images:
          - "debian12"
          - "ubuntu2204"
          - "sles15sp5"
          - "tumbleweed"
        scenario:
          - "package"
    container:
      image: ghcr.io/pandemonium1986/alpine313:nightly
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${{ github.workspace }}:/opt/workspace/${{ github.repository }}
      env:
        ANSIBLE_FORCE_COLOR: "1"
        PY_COLORS: "1"
        DKR_IMAGE: ${{ matrix.images }}
        DKR_TAG: "nightly"
      options: >-
        --workdir /opt/workspace/${{ github.repository }}
    needs:
      - lint
    steps:
      - name: "Init: Run checkout"
        uses: actions/checkout@v4
      - name: "Molecule: Create"
        run: molecule create --scenario-name ${{ matrix.scenario }}
      - name: "Molecule: Converge"
        run: molecule converge --scenario-name ${{ matrix.scenario }}
      - name: "Molecule: Idempotence"
        run: molecule idempotence --scenario-name ${{ matrix.scenario }}
      - name: "Molecule: Verify"
        run: molecule verify --scenario-name ${{ matrix.scenario }}
      - name: "Molecule: Destroy"
        run: molecule destroy --scenario-name ${{ matrix.scenario }}
  molecule-get-pip:
    name: "Molecule: get-pip scenario"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        images:
          - "centos7"
          - "sles15sp3"
        scenario:
          - "get-pip"
    container:
      image: ghcr.io/pandemonium1986/alpine313:nightly
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ${{ github.workspace }}:/opt/workspace/${{ github.repository }}
      env:
        ANSIBLE_FORCE_COLOR: "1"
        PY_COLORS: "1"
        DKR_IMAGE: ${{ matrix.images }}
        DKR_TAG: "nightly"
      options: >-
        --workdir /opt/workspace/${{ github.repository }}
    needs:
      - lint
    steps:
      - name: "Init: Run checkout"
        uses: actions/checkout@v4
      - name: "Molecule: Create"
        run: molecule create --scenario-name ${{ matrix.scenario }}
      - name: "Molecule: Converge"
        run: molecule converge --scenario-name ${{ matrix.scenario }}
      - name: "Molecule: Idempotence"
        run: molecule idempotence --scenario-name ${{ matrix.scenario }}
      - name: "Molecule: Verify"
        run: molecule verify --scenario-name ${{ matrix.scenario }}
      - name: "Molecule: Destroy"
        run: molecule destroy --scenario-name ${{ matrix.scenario }}
